Updating precommit hook

diff --git a/common/git-hooks/pre-commit b/common/git-hooks/pre-commit
--- a/common/git-hooks/pre-commit
+++ b/common/git-hooks/pre-commit
@@ -1,31 +1,60 @@
-#!/bin/sh
+#!/bin/bash
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 
-FILELIST=`git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx|ts|tsx|vue)$'`
+REVISION=$(git log --pretty=format:'%h' -n 1)
+FILE_LIST=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx|ts|tsx|vue)$')
+
+echo "$FILE_LIST"
+
+FILE_COUNT=${#$FILELIST[@]}
+
+echo "$FILE_COUNT"
+
+FILE_STRING='file'
+
+if [ "$FILE_COUNT" -gt 1 ]; then
+    FILE_STRING='files'
+fi
 
 ESLINT=common/temp/node_modules/.bin/eslint
 PRETTIER=common/temp/node_modules/.bin/pretty-quick
 
-APPS_RUN_GENERATOR=apps/run-generator/src/**/*.{ts,vue}
-TOOLS_GAME_MECHANICS=tools/game-mechanics/src/**/*.ts
+BOLD=`tput bold`
+NORMAL=`tput sgr0`
 
 echo --------------------------------------------
 echo Starting Git hook: pre-commit
+echo --------------------------------------------
 
-echo ESLINT
+echo Running ESLint
 
-if [ ${#fileList} -lt 1 ]; then
-    echo -e "You have no staged files to lint\n"
-    exit
-fi
+if [ -f $ESLINT ]; then
+    echo "🔍 Finding changed files since ${BOLD}git${NORMAL} revision ${BOLD}$REVISION${NORMAL}."
+    echo $FILE_COUNT
 
-echo -e `$ESLINT ${fileList[*]} "$@"`
+    echo "🎯 Found ${BOLD}${FILE_COUNT}${NORMAL} changed $FILE_STRING."
 
-if [ $? -ne 0 ]; then
-    echo -e "\nPlease fix the above linting issues before committing.\n"
-    exit 1
+    if [ "$FILE_COUNT" -gt 0 ]; then
+        echo $FILE_LIST
+        
+        echo 'first'
+        echo $FILE_LIST[*]
+
+        echo 'second'
+        echo ${FILE_LIST[*]}
+
+        $ESLINT ${FILE_LIST[*]} "$@"
+    fi
+
+    if [ $? -ne 0 ]; then
+        echo "⛔️  Check failed, please fix the above issues before committing."
+    else
+        echo "✅  Everything is awesome!"
+    fi
+else
+  echo "\nError running ESLINT: $ESLINT\n"
 fi
 
 # if [ -f $ESLINT ]; then
@@ -38,12 +67,14 @@ fi
 #   echo Error running ESLINT: $ESLINT
 # fi
 
+echo Running Prettier
+
 if [ -f $PRETTIER ]; then
-  echo Invoking $PRETTIER
   $PRETTIER
 else
-  echo Error running PRETTIER: $PRETTIER
+  echo "\nError running PRETTIER: $PRETTIER\n"
 fi
 
+echo --------------------------------------------
 echo Finished Git hook: pre-commit
 echo --------------------------------------------
